# Generated by Django 2.2.19 on 2021-03-15 15:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Username', models.CharField(max_length=30, unique=True)),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Story_Headline', models.CharField(max_length=64)),
                ('Story_Category', models.CharField(max_length=6)),
                ('Story_Region', models.CharField(max_length=2)),
                ('Post_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Story_Details', models.CharField(max_length=512)),
                ('Authors', models.ManyToManyField(to='story.Author')),
            ],
        ),
    ]
