# Generated by Django 2.2.19 on 2021-03-15 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='Post_Date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='Story_Category',
            field=models.CharField(choices=[('pol', 'politics'), ('art', 'art_news'), ('tech', 'technology_new'), ('trivia', 'trivial_news')], default='trivia', max_length=6),
        ),
        migrations.AlterField(
            model_name='story',
            name='Story_Region',
            field=models.CharField(choices=[('uk', 'United_Kingdom_news'), ('eu', 'European_news'), ('w', 'world_news')], default='uk', max_length=2),
        ),
    ]
